### ISSUE TITLE
Add wrapper for https://github.com/cytoscape/cytoscape.js

### ISSUE THREAD

**Issue by lemmy** [afonsonf/tlaplus-html-examples#1]
TLA+ wrappers for https://github.com/cytoscape/cytoscape.js would be rad.

**Comment by afonsonf** [comment]
Hi, thank you for the suggestion, however currently I do not have the time to do it 

For simpler graphs I point to a recent project I did where I used https://github.com/visjs/vis-network
project: https://github.com/afonsonf/tlaplus-finite-automata
demo: https://afonsonf.github.io/tlaplus-finite-automata/html/examples/enfa.html
